name: openapi_generator
description: Generate openapi client source code for dart.
version: 0.0.1
# homepage: https://www.example.com

environment:
  sdk: '>=2.7.0 <3.0.0'

#dependencies:
#  path: ^1.6.0

dependencies:
  build: ^1.2.2

dev_dependencies:
  pedantic: ^1.8.0
  build_config: ^0.4.2
  build_runner: ^1.7.4
  test: ^1.6.0

executables:
  openapi-generator: main
