name: openapi_generator_annotations
description: A starting point for Dart libraries or applications.
version: 0.0.2-dev
homepage: https://github.com/gibahjoe/openapi-generator-dart


environment:
  sdk: '>=2.7.0 <3.0.0'

#dependencies:
#  path: ^1.6.0

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
