openapi: 3.0.1
info:
  title: Currency Rate API
  description: Currency rate api.
  license:
    name: ''
    url: ''
  version: '1.0'
servers:
  - url: 'http://18.191.217.126:8080/currency-rate-api'
    description: Generated server url
security:
  - Authorization: []
paths:
  /login:
    post:
      tags:
        - authentication-controller
      operationId: doLogin
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginDto'
        required: true
      responses:
        '200':
          description: default response
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ApiResponseString'
        '400':
          description: default response
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ApiResponseObject'
        '404':
          description: default response
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ApiResponseObject'
        '500':
          description: default response
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ApiResponseObject'
  /countries:
    get:
      tags:
        - country-controller
      operationId: getCountries
      parameters:
        - name: limit
          in: query
          required: false
          schema:
            type: integer
            format: int64
        - name: offset
          in: query
          required: false
          schema:
            type: integer
            format: int64
        - name: codeISO3166
          in: query
          schema:
            type: string
        - name: id
          in: query
          schema:
            type: integer
            format: int64
        - name: countryName
          in: query
          schema:
            type: string
        - name: shortName
          in: query
          schema:
            type: string
        - name: dialingCode
          in: query
          schema:
            type: string
        - name: status
          in: query
          schema:
            type: string
            enum:
              - ACTIVE
              - INACTIVE
      responses:
        '200':
          description: default response
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/QueryResultsCountry'
        '400':
          description: default response
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ApiResponseObject'
        '404':
          description: default response
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ApiResponseObject'
        '500':
          description: default response
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ApiResponseObject'
  '/currencies/{code}':
    get:
      tags:
        - currency-controller
      operationId: getCurrency
      parameters:
        - name: code
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: default response
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Currency'
        '400':
          description: default response
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ApiResponseObject'
        '404':
          description: default response
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ApiResponseObject'
        '500':
          description: default response
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ApiResponseObject'
    patch:
      tags:
        - currency-controller
      operationId: updateCurrency
      parameters:
        - name: code
          in: path
          required: true
          schema:
            type: string
        - name: countryId
          in: query
          required: false
          schema:
            type: integer
            format: int64
        - name: symbol
          in: query
          required: false
          schema:
            type: string
        - name: name
          in: query
          required: false
          schema:
            type: string
        - name: description
          in: query
          required: false
          schema:
            type: string
      responses:
        '200':
          description: default response
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Currency'
        '400':
          description: default response
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ApiResponseObject'
        '404':
          description: default response
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ApiResponseObject'
        '500':
          description: default response
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ApiResponseObject'
  /currencies/supported-currencies:
    get:
      tags:
        - currency-controller
      operationId: getSupportedCurrencies
      parameters:
        - name: limit
          in: query
          required: false
          schema:
            type: integer
            format: int64
        - name: requiresUpdate
          in: query
          required: false
          schema:
            type: boolean
        - name: hasRates
          in: query
          required: false
          schema:
            type: boolean
        - name: offset
          in: query
          required: false
          schema:
            type: integer
            format: int64
        - name: symbol
          in: query
          schema:
            type: string
        - name: country
          in: query
          schema:
            type: integer
            format: int64
        - name: name
          in: query
          schema:
            type: string
        - name: description
          in: query
          schema:
            type: string
        - name: codeISO4217
          in: query
          schema:
            type: string
        - name: id
          in: query
          schema:
            type: integer
            format: int64
        - name: status
          in: query
          schema:
            type: string
            enum:
              - ACTIVE
              - INACTIVE
      responses:
        '200':
          description: default response
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/QueryResultsCurrency'
        '400':
          description: default response
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ApiResponseObject'
        '404':
          description: default response
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ApiResponseObject'
        '500':
          description: default response
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ApiResponseObject'
  /currencies/rates/latest-with-inverse:
    get:
      tags:
        - currency-rate-controller
      operationId: getLatestRatesWithInverse
      responses:
        '200':
          description: default response
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/CurrencyRatesWithInverseResponsePojo'
        '400':
          description: default response
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ApiResponseObject'
        '404':
          description: default response
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ApiResponseObject'
        '500':
          description: default response
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ApiResponseObject'
  '/currencies/rates/latest/{baseCurrencyCode}':
    get:
      tags:
        - currency-rate-controller
      operationId: getLatestRates
      parameters:
        - name: baseCurrencyCode
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: default response
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/CurrencyRatesResponsePojo'
        '400':
          description: default response
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ApiResponseObject'
        '404':
          description: default response
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ApiResponseObject'
        '500':
          description: default response
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ApiResponseObject'
  /currencies/rates:
    get:
      tags:
        - currency-rate-controller
      operationId: getCurrencyRate
      parameters:
        - name: limit
          in: query
          required: false
          schema:
            type: integer
            format: int64
        - name: offset
          in: query
          required: false
          schema:
            type: integer
            format: int64
        - name: baseCurrencyCode
          in: query
          schema:
            type: string
        - name: targetCurrency
          in: query
          schema:
            type: string
        - name: sourceCurrency
          in: query
          schema:
            type: string
        - name: dataSource
          in: query
          schema:
            type: string
        - name: targetCurrencyCode
          in: query
          schema:
            type: string
        - name: status
          in: query
          schema:
            type: string
            enum:
              - ACTIVE
              - INACTIVE
      responses:
        '200':
          description: default response
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/QueryResultsCurrencyRate'
        '400':
          description: default response
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ApiResponseObject'
        '404':
          description: default response
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ApiResponseObject'
        '500':
          description: default response
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ApiResponseObject'
  /permission-types:
    get:
      tags:
        - records-controller
      operationId: getPermissionTypes
      responses:
        '200':
          description: default response
          content:
            '*/*':
              schema:
                type: array
                items:
                  type: string
                  enum:
                    - UPDATE
                    - VIEW
        '400':
          description: default response
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ApiResponseObject'
        '404':
          description: default response
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ApiResponseObject'
        '500':
          description: default response
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ApiResponseObject'
  /users:
    post:
      tags:
        - user-controller
      operationId: createUser
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewUserDto'
        required: true
      responses:
        '200':
          description: default response
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/User'
        '400':
          description: default response
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ApiResponseObject'
        '404':
          description: default response
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ApiResponseObject'
        '500':
          description: default response
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ApiResponseObject'
components:
  schemas:
    ApiResponseObject:
      type: object
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
        data:
          type: object
    LoginDto:
      required:
        - password
        - userName
      type: object
      properties:
        userName:
          type: string
        password:
          type: string
    ApiResponseString:
      type: object
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
        data:
          type: string
    Country:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        shortName:
          type: string
        dialingCode:
          type: string
        codeISO3166:
          type: string
        status:
          type: string
          enum:
            - ACTIVE
            - INACTIVE
    QueryResultsCountry:
      type: object
      properties:
        limit:
          type: integer
          format: int64
        offset:
          type: integer
          format: int64
        total:
          type: integer
          format: int64
        results:
          type: array
          items:
            $ref: '#/components/schemas/Country'
        empty:
          type: boolean
    Currency:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        codeISO4217:
          type: string
        description:
          type: string
        symbol:
          type: string
        status:
          type: string
          enum:
            - ACTIVE
            - INACTIVE
        country:
          $ref: '#/components/schemas/Country'
    QueryResultsCurrency:
      type: object
      properties:
        limit:
          type: integer
          format: int64
        offset:
          type: integer
          format: int64
        total:
          type: integer
          format: int64
        results:
          type: array
          items:
            $ref: '#/components/schemas/Currency'
        empty:
          type: boolean
    CurrencyPairPojo:
      type: object
      properties:
        baseCurrencyCode:
          type: string
        targetCurrencyCode:
          type: string
        rate:
          type: number
    CurrencyRatesWithInverseResponsePojo:
      type: object
      properties:
        timeStamp:
          type: integer
          format: int64
        rates:
          type: array
          items:
            $ref: '#/components/schemas/CurrencyPairPojo'
    CurrencyRatesResponsePojo:
      type: object
      properties:
        timeStamp:
          type: integer
          format: int64
        baseCurrencyCode:
          type: string
        rates:
          type: object
          additionalProperties:
            type: number
    CurrencyRate:
      type: object
      properties:
        id:
          type: integer
          format: int64
        rate:
          type: number
        timeInMillis:
          type: integer
          format: int64
        dateCreated:
          type: string
          format: date-time
        status:
          type: string
          enum:
            - ACTIVE
            - INACTIVE
        dataSource:
          type: string
        sourceCurrency:
          $ref: '#/components/schemas/Currency'
        targetCurrency:
          $ref: '#/components/schemas/Currency'
    QueryResultsCurrencyRate:
      type: object
      properties:
        limit:
          type: integer
          format: int64
        offset:
          type: integer
          format: int64
        total:
          type: integer
          format: int64
        results:
          type: array
          items:
            $ref: '#/components/schemas/CurrencyRate'
        empty:
          type: boolean
    NewUserDto:
      required:
        - firstName
        - password
        - permissions
        - userType
        - username
      type: object
      properties:
        permissions:
          maxItems: 2147483647
          minItems: 1
          type: array
          items:
            type: string
            enum:
              - UPDATE
              - VIEW
        firstName:
          type: string
        lastName:
          type: string
        userType:
          type: string
          enum:
            - ADMIN
            - APP
            - OTHER
        username:
          type: string
        email:
          type: string
        password:
          type: string
    Permission:
      type: object
      properties:
        id:
          type: integer
          format: int64
        type:
          type: string
          enum:
            - UPDATE
            - VIEW
    User:
      type: object
      properties:
        id:
          type: integer
          format: int64
        firstName:
          type: string
        lastName:
          type: string
        displayName:
          type: string
        userType:
          type: string
          enum:
            - ADMIN
            - APP
            - OTHER
        secretKey:
          type: string
        active:
          type: boolean
        username:
          type: string
        email:
          type: string
        permissions:
          type: array
          items:
            $ref: '#/components/schemas/Permission'
  securitySchemes:
    Authorization:
      type: apiKey
      name: Authorization
      in: header
