name: openapi_generator
description: Generate openapi client source code for dart.
version: 0.0.1
# homepage: https://www.example.com

environment:
  sdk: '>=2.7.0 <3.0.0'

#dependencies:
#  path: ^1.6.0

dependencies:
  build: ^1.2.2
  source_gen: ^0.9.0
  path: ^1.6.4
  cli_util: ^0.1.3+2
  jaguar_retrofit: ^2.8.8
  jaguar_serializer: ^2.2.12
  openapi_generator_annotations:
    path: ../openapi-generator-annotations/

dev_dependencies:
  pedantic: ^1.8.0
  build_config: ^0.4.2
  build_runner: ^1.7.4
  test: ^1.6.0
  jaguar_retrofit_gen: ^2.8.10
  jaguar_serializer_cli: ^2.2.8

executables:
  openapi-generator: main
