name: openapi_generator
description: Generator for openapi client sdk inspired by the npm impplementation of openapi-generator-cli.
version: 1.0.8
homepage: https://github.com/gibahjoe/openapi-generator-dart

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  build: ^1.2.2
  source_gen: ^0.9.5
  path: ^1.6.4
  openapi_generator_annotations: ^1.0.8
  analyzer: ^0.39.8
  openapi_generator_cli: ^1.0.8

dev_dependencies:
  pedantic: ^1.9.0
  build_config: ^0.4.2
  build_runner: ^1.9.0
  test: ^1.14.3
