name: openapi_generator
description: Generator for openapi client sdk inspired by the npm impplementation of openapi-generator-cli.
version: 1.0.5
homepage: https://github.com/gibahjoe/openapi-generator-dart

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  build: ^1.2.2
  source_gen: ^0.9.0
  path: ^1.6.4
  cli_util: ^0.1.3+2
  openapi_generator_annotations: ^1.0.3
  analyzer: ^0.39.4
  openapi_generator_cli: ^1.0.5

dev_dependencies:
  pedantic: ^1.8.0
  build_config: ^0.4.2
  build_runner: ^1.7.4
  test: ^1.6.0
