name: openapi_generator
description: Generator for openapi client sdk inspired by the npm impplementation of openapi-generator-cli.
version: 1.1.4
homepage: https://github.com/gibahjoe/openapi-generator-dart

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  build: '>=1.3.0 <=1.10.3'
  source_gen: ^0.9.10
  path: ^1.7.0
  openapi_generator_annotations: ^1.1.4
  analyzer: ^0.41.1
  openapi_generator_cli: ^1.1.4
#  generic_reader: ^0.1.5

dev_dependencies:
  pedantic: ^1.9.2
  build_config: ^0.4.5
  build_runner:
  test: ^1.15.7
